//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by privatisation.rc
//
#define IDC_NEW                         3
#define IDC_CLEAN                       4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PRIVATISATION_FORM          101
#define IDB_SPLASH                      102
#define IDR_MAINFRAME                   128
#define IDR_PRIVATTYPE                  129
#define IDD_SEARCH                      130
#define IDI_SAVE                        132
#define IDI_LAST                        134
#define IDI_FIND                        135
#define IDI_CLOSEALL                    136
#define IDI_CLOSEALLD                   137
#define IDI_CALENDAR                    141
#define IDI_CLOSE                       142
#define IDI_DELETE                      143
#define IDI_ADDRESS                     146
#define IDD_DTP                         147
#define IDD_DECLARE                     148
#define IDD_CONTRACT                    150
#define IDD_REPLICA                     151
#define IDD_WARRANT                     152
#define IDD_WRNT_PEOPLE                 154
#define IDD_WRNT_WRNT                   155
#define IDI_ADD                         155
#define IDD_WRNT_SETUP                  156
#define IDI_REMOVE                      156
#define IDI_ROOT                        157
#define IDI_CURRENT                     158
#define IDI_BIND                        159
#define IDI_CONTRACT                    160
#define IDI_DECLARE                     161
#define IDI_WARRANT                     162
#define IDI_REPLICA                     163
#define IDI_PERSONS                     164
#define IDI_W_SETUP                     165
#define IDI_W_WRNT                      166
#define IDI_P_ADD                       168
#define IDI_P_REMOVE                    169
#define IDI_SEARCH                      171
#define IDD_BH                          173
#define IDD_ADDRESS                     175
#define IDD_PERIOD_DISTRICT             176
#define IDD_PERIOD                      177
#define IDD_ADDRESS_FILTER              178
#define IDD_PERIOD_BH                   180
#define IDI_OWNER                       181
#define IDI_NOTOWNER                    182
#define IDD_LOGIN                       183
#define IDI_LOCK                        185
#define IDI_FOLDER                      186
#define IDI_POST                        187
#define IDD_REPLIST                     189
#define IDD_USERSETUP                   190
#define IDD_NEWADDRESS                  191
#define IDD_INFO                        195
#define IDI_UNBIND                      196
#define IDD_BASE                        197
#define IDD_APPEAL                      199
#define IDC_LIST                        1000
#define IDC_STREET                      1001
#define IDC_BUILDING                    1002
#define IDC_PART                        1003
#define IDC_FLATNUM                     1004
#define IDC_FLAT                        1004
#define IDC_FAMILY                      1005
#define IDC_EXTFLAT                     1005
#define IDC_NAME                        1006
#define IDC_SURNAME                     1007
#define IDC_NUM                         1008
#define IDC_BOOK                        1009
#define IDC_EXPORT                      1010
#define IDC_INFO                        1011
#define IDC_DEPDATE                     1013
#define IDC_CAL                         1014
#define IDC_DATE_LOT                    1015
#define IDC_DATE_LOT_B                  1016
#define IDC_DATE_REG                    1017
#define IDC_DATE_REG_B                  1018
#define IDC_DATE_RECORD                 1019
#define IDC_END                         1019
#define IDC_DATE_RECORD_B               1020
#define IDC_END_B                       1020
#define IDC_CALENDAR                    1021
#define IDC_DATE_ACT                    1021
#define IDC_DATE_ACT_B                  1022
#define IDC_DATE_CANCEL                 1025
#define IDC_DATE_CANCEL_B               1026
#define IDC_REGDEP                      1027
#define IDC_FLATTYPE                    1028
#define IDC_PROPERTYTYPE                1029
#define IDC_PRIVSQR                     1030
#define IDC_FLAT_PART                   1031
#define IDC_PRIVROOMS                   1032
#define IDC_ADDFLAT                     1033
#define IDC_TAB                         1034
#define IDC_COMMENTS                    1036
#define IDC_OWNER_REMOVE                1038
#define IDC_OWNER_ADD                   1039
#define IDC_REFUSER_REMOVE              1040
#define IDC_REFUSER_ADD                 1041
#define IDC_BH                          1043
#define IDC_TREE                        1045
#define IDC_PERSON_REMOVE               1047
#define IDC_FREE_ROOT                   1047
#define IDC_FREE_CURRENT                1048
#define IDC_OWNERS                      1049
#define IDC_REFUSERS                    1050
#define IDC_OWNER_ROOT                  1051
#define IDC_ADD                         1051
#define IDC_OWNER_CURRENT               1052
#define IDC_REMOVE                      1052
#define IDC_REFUSER_ROOT                1053
#define IDC_BIND                        1053
#define IDC_REFUSER_CURRENT             1054
#define IDC_UNBIND                      1054
#define IDC_VERB                        1055
#define IDC_INTHENAME                   1056
#define IDC_AGREEMENT                   1057
#define IDC_PERMIT                      1059
#define IDC_ROOM_QUANT                  1060
#define IDC_FULL_SQR                    1061
#define IDC_LIVE_SQR                    1062
#define IDC_FLAT_COST                   1063
#define IDC_BUILDING_SQR                1064
#define IDC_BUILDING_COST               1065
#define IDC_COEF                        1066
#define IDC_LOT_NUM                     1067
#define IDC_SHARE_SQR                   1068
#define IDC_LOT_COST                    1069
#define IDC_REG_NUM                     1070
#define IDC_BOOK_NUM                    1071
#define IDC_NORM                        1072
#define IDC_PAYMENT                     1073
#define IDC_BH_B                        1074
#define IDC_DATE_BUILT                  1075
#define IDC_DATE_BUILT_B                1076
#define IDC_COMMENTS_TEXT               1077
#define IDC_TRANS                       1078
#define IDC_PREVIEW                     1079
#define IDC_TEXT                        1080
#define IDC_TMPEDIT                     1081
#define IDC_TMPDATE                     1083
#define IDC_TMPDATE_B                   1084
#define IDC_DATA                        1085
#define IDC_CHIEF                       1088
#define IDC_GROUND                      1089
#define IDC_LOWER                       1090
#define IDC_UPPER                       1091
#define IDC_SIGN                        1092
#define IDC_ADDRESS                     1093
#define IDC_SAVE                        1096
#define IDC_DISTRICT                    1097
#define IDC_BEGIN                       1098
#define IDC_BEGIN_B                     1099
#define IDC_LOGIN                       1103
#define IDC_PASSWORD                    1104
#define IDC_STATUS                      1105
#define IDC_USER                        1107
#define IDC_SIGN1                       1108
#define IDC_SIGN2                       1109
#define IDC_STAT1                       1110
#define IDC_DATE                        1112
#define ID_RECORD_FIND                  32771
#define ID_RECORD_ADDRESS               32772
#define ID_SETUP_APP                    32775
#define ID_RECORD_EXPORT                32776
#define ID_WINDOW_CLOSEALL              32777
#define ID_CONTRACT_SAVE                32778
#define ID_CONTRACT_DELETE              32779
#define ID_CONTRACT_ADDRESS             32780
#define ID_CONTRACT_CLOSE               32781
#define ID_PRIV_CONTRACT                32782
#define ID_PRIV_DECLARE                 32783
#define ID_PRIV_WARRANT                 32784
#define ID_PRIV_REPLICA                 32785
#define ID_LIST_INFO                    32786
#define ID_LIST_REPORT                  32787
#define ID_LIST_REPORT_DEP              32788
#define ID_LIST_INJURY                  32789
#define ID_LIST_INJURY_SQR              32790
#define ID_LIST_CONCLUSION              32791
#define ID_LIST_CANCEL                  32792
#define ID_LIST_CANCEL_DEP              32793
#define ID_LIST_SIGNED                  32794
#define ID_LIST_SIGNED_DEP              32795
#define ID_LIST_TAX                     32796
#define ID_LIST_FLATTYPE                32797
#define ID_MAKE_DECLARATION             32800
#define ID_MAKE_DECLARATION_DEP         32801
#define ID_MAKE_DECLARATION_REG         32802
#define ID_MAKE_CONTRACT                32803
#define ID_MAKE_REPLICA                 32804
#define ID_MAKE_INJUIRY                 32806
#define ID_SETUP_USER                   32807
#define ID_LIST_BASE                    32808

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
